# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq_management
      
      ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
      - 5672:5672
      
      volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
      environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = passw123

      restart: always
volumes:
  postgres:
